package tools

import "context"

// ParamSchema describes a single parameter of a tool.
type ParamSchema struct {
	Type        string // "string" | "int" | "bool"
	Description string
	Required    bool
}

// ToolSchema is the static definition of a tool exposed to the LLM.
type ToolSchema struct {
	Name        string
	Description string
	Params      map[string]ParamSchema
	Permission  PermissionLevel
}

// ToolCall is a request from the LLM to invoke a tool.
type ToolCall struct {
	// ID links this call to its result; generated by the parser.
	ID     string
	Name   string
	Params map[string]any
}

// ToolResult is the outcome of executing a ToolCall.
type ToolResult struct {
	CallID  string
	Success bool
	// Output is the text content returned to the LLM in the next conversation turn.
	Output string
}

// Tool is the interface that all git (and future) tools must implement.
type Tool interface {
	Schema() ToolSchema
	Execute(ctx context.Context, call ToolCall) ToolResult
}
